### ISSUE TITLE
Create vision document

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-docs#2]
## Issue description
Create vision document for the product, defining what is the product, who is making it, target audience, main features and restrictions.

Document must have a revision history, introduction and references.

You can decide the overall topic organization.

## Additional context
Document Example: https://translate-me.github.io/docs/documentos/projeto/doc_de_visao/
Guide: https://www.ibm.com/support/knowledgecenter/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by tsrrodrigues** [comment]
### Dúvida em relação às Restrições no Documento de Visão
#### Restrições de Design
Estamos em dúvida sobre quais as restrições de design do projeto. É necessário esperar o documento de identidade visual para preencher este tópico? Caso não, quais seriam as restrições de design?
#### Restrições de Implementação
Estamos em dúvida em relação à todas as tecnologias que iremos utilizar. Podemos usar o quadro de conhecimentos como base? Se não, há outro documento que liste estas tecnologias?

**Comment by renan601** [comment]
> ### Dúvida em relação às Restrições no Documento de Visão
> #### Restrições de Design
> 
> Estamos em dúvida sobre quais as restrições de design do projeto. É necessário esperar o documento de identidade visual para preencher este tópico? Caso não, quais seriam as restrições de design?
> #### Restrições de Implementação
> 
> Estamos em dúvida em relação à todas as tecnologias que iremos utilizar. Podemos usar o quadro de conhecimentos como base? Se não, há outro documento que liste estas tecnologias?

Essa parte de restrições são itens que o software deve cumprir por algum motivo, seja por uma lei que obrigue ou uma decisão da equipe para atender bem ao público-alvo. 
Portanto, nessa parte de restrições de design, cabe dizer como o software deve se comportar, como será sua usabilidade/acessibilidade.
Na parte de restrições de implementação pode usar o quadro de conhecimento sim, se formos adicionar novas tecnologias podemos editar o doc depois refletindo essa mudança.

**Comment by lboaventura25** [comment]
### Dúvida em relação aos últimos pontos do Documento de Visão

#### Requisitos

Estamos com dúvida sobre o quadro de requisitos do produto. Ele deve ser colocado desde já ou falta alguma parte pra fechar os requisitos? 

#### Usabilidade

Estamos em dúvida se já podemos escrever essa parte do documento, visto que ainda não sabemos o design da aplicação.

**Comment by renan601** [comment]
> ### Dúvida em relação aos últimos pontos do Documento de Visão
> #### Requisitos
> 
> Estamos com dúvida sobre o quadro de requisitos do produto. Ele deve ser colocado desde já ou falta alguma parte pra fechar os requisitos?
> #### Usabilidade
> 
> Estamos em dúvida se já podemos escrever essa parte do documento, visto que ainda não sabemos o design da aplicação.

Podem usar os Requisitos que estão listados aqui: https://docs.google.com/document/d/1YkmmSva-du90GnxspxScE9FuU1CMJk-tWI2EwthyzAo/edit
Não fechamos completamente, mas qualquer alteração podemos modificar o documento

Quanto ao tópico de Usabilidade podem esperar o doc de Identidade Visual se não se sentirem confortáveis para escrevê-lo agora. Mas já temos alguns objetivos claros para a aplicação, como um design intuitivo se baseando no padrão já conhecido do Google Maps, podem falar sobre isso para que o tópico não fique em branco.
