### ISSUE TITLE
Review and correct documents

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-docs#62]
## Issue Description
Review and make necessary corrections to project documents.
For each revised document, check the respective checkbox.

## Documents:
- [x] Visual identity - Brenda
- [x] Personas - Brenda e Lucas
- [x] Product Backlog - Renan
- [x] Prototype - Brenda
- [x] Vision document - Brenda e Renan
- [x] Product Roadmap
- [x] Papers Roadmap
- [x] Architecture - Sara
- [x] Project Analytical Structure
- [x] Devops tools - Rossicler
- [x] Management and Software Configuration Plan - Rossicler
- [x] Pipelines - Rossicler
- [x] Risk management
- [x] Project Arbeture Term - Renan
- [x] Sprints documentation - Renan
- [x] Definition of methodology - Renan
- [x] Quality - Sara
- [x] Costs 
- [x] Readmes of Repositories

**Comment by silvasara** [comment]
- Identidade visual:
   * Mudar o nome que aparece na lateral
   * atualizar a logo
   * atualizar a cor primária e secundárias
- Personas:
   * Explicar um pouco mais a técnica de persnonas na introdução
   * Colocar o tópico de objetivo antes da apresentação das pesonas
   * colocar referências
- Protótipo:
   * colocar a ferramenta que foi utlizada
   * Incluir o link pro protótipo
   * Atualizar as telas
- Documento de visão:
   * no tópico 1.3 deixar apenas os acrônimos que são usados no documento
   * no tópico 2.1 citar referência para o que foi dito sobre o cenário brasileiro
   * os tópicos 2.2 e 2.3 pode ser um texto, não precisa ser uma tabela
   * o tópico 3.1 poderia está depois de apresentar as partes interessadas
   * o tópico "Alternativas e concorrência precisa ser mais elaborado e pode ficar fora da seção 3
   * Padronizar o tempo verbal
   * Atualizar o tópico 4.2 pro escopo e priorides atuais do projeto
   * todo o tópico 5 precisa ser atualizado pro escopo e prioridades atuais do projeto. Os textos das funcionalidades que serão mantidas precisa ser revisado também
   * citar e linkar o documento de indentidade visual no tópico 6.1
   * citar e linkar o documento de arquitetura no tópico 6.3
   * No tópico 7 retirar os subtópicos e citar o doc de qualidade
   *  Atualizar o tópico 8 pro escopo e priorides atuais do projeto e talvez mudar a posição dele, colocar antes de tópicos menos importantes
- Arquitetura:
   * Atualizar os modelos de dados
   * Melhorar a descrição dos componentes dos serviços
   * Atualizar componentes do serviço de sercretaria
   * Atualizar componentes do front end
- Gerenciamento de custos:
   * Tirar o termo júnior de gerente
   * Atualizar descrição de custo de servidor pra um servidor pra homologação e outro pra produção, com os dois serviços de backed em cada um
   * Corrigir descrição do github pages
   * Por siginifcado de CEB
- Ferramentas de DevOps:
  * Colocar no documento de gcs
  * descrever brevemente as ferramentas
- Plano de Gerência e Configuração de Software:
  * tirar a tabela de ferramentas ja que o doc de ferramentas de devops vai vir pra esse documento
  * Podeira ser uma seção pra cada política, em vez de ficarem como subtópicos do 3
  * "Se a issue tratar de uma história do Backlog do Produto, seu título deve ser o código da história mais a descrição desta." tirar isso do tópico 3.1, nós não fazemos isso
  * colocar o título do tópico 3.2.1 no plural
  * O tópico de Política de Apovação poderia ser um subtópico do tópico política de PR
  * deixar o tópico 3.5 Política de Documentação por último
  * incluir no tópico de PR que o a branch só será merjada após duas aprovações no PR
- Definição de Metodologia: 
  * As imagens usadas são originais? se não for, colocar referência
  * "XP é um apelido carinhoso" acredito que seja só a sigla mesmo 
  * IBM RUP é uma biblioteca?
  * "nenhuma das metodologias puristas se encaixava em nosso contexto" as metodologias não são puristas.
  * no tópico 3.1 explicar melhor as responsabilidades de DevOps
  * no tópico 3.2 falar que cada card é uma issue do GitHub
  * colocar quais as colunas que usamos
  * algumas siglas precisam ser escritras por extenso ou colocar um tópico de acronimos: TDD, MoSCow, UML, PMBOK, TAP, EAP
  * Incluir no último parágrafo do tópico 5 que essas métriac também influenciam no custo do projeto
- Pipelines:
  * Mover esse documento para o documento de GCS
  * Dizer que a pipeline descrita é a de CI, e explicar brevemente o que seria CI
  * Colocar o que faz "quebrar" a pipeline, por exemplo: testes que falham, nota abaixo de 8 no pylint
 - Qualidade:
   * Verificar os tempos verbais: colocar no presente o que já fazemos e colocar no futuro o que ainda não fazemos/ pretedemos fazer
   * colocar o que é ANSI no tópico 2
   * os tópicos da seção 2 estão "quebrados"
   * no tópico 2 falar sobre ambiente de produção e homologação
   * corrigir "dados pessoas" no tópico 4
   * no tópico 5 colocar o seria lint
   * "suite de testes para garantir o funcionamento das funcionalidades" trocar para "suite de testes para garantir o correto comportamento das funcionalidades" no tópico 5
   * Incluir cobertura de teste esperada
   * colocar nota aceitavel pela ferramenta de análise de codigo
   * No tópico 6 explicar brevemente o que serião as heurísitcas de nielsen
   * No tópico 6 corrigir alguns erros de concordância com o plural e elaborar mais
- Termo de Abertura do Projeto:
  * precisa ter essa tabela de partes interessadas aqui? ela ja é mostrada no doc de visão
  * citar/linkar os doc de qualidade de custos
- Sprints:
  * Verificar datas de inicio e de término nos documentos de planejamento e de review de todas as sprints
  * Verificar os tópicos de membros presentes nos documentos de planejamento e e de review de todas as sprints (em algumas reuniões alguns membros faltam, mas em todos os documentos estão como todos presentes)
  * Verificar escrita dos textos e links
- Não vi necessidade de correções ou melhorias nos documentos de EAP, Backlog, Rodmaps de Papéis e de Produto e no de Gerenciamento de Riscos

**Comment by renan601** [comment]
* Personas
Transformar o documento em técnicas de definição de produto
Colocar tópico sobre entrevistas, brainstorming e personas
Definir cada uma das técnicas, explicar o porquê utilizamos e colocar os artefatos produzidos em cada uma delas
Adicionar referências

**Comment by lboaventura25** [comment]
- Readme do repositório da Secretaria
    - O comando de build e up do docker está errado, trocar web por api ou só up e build.
